version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: food_trucks
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 30
    volumes:
      - db:/var/lib/mysql
  backend:
    build:
      context: .
    container_name: backend
    environment:
      GOOGLE_API_KEY: KEY
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
volumes:
  db: